name: API Tests

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install Newman and plugin
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: 运行测试
        run: |
          newman run JSONPlaceholder-Tests.postman_collection.json \
            -e jsonplaceholder-env.postman_environment.json \
            -d test-data.csv \
            -r cli,htmlextra \
            --reporter-htmlextra-export reports/report-${{ github.run_id }}.html
      - name: 上传报告
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/
